version: 2.1

jobs:
  # Job for build for other branches
  build:
    docker:
      - image: cimg/node:20.11.0

    working_directory: ~/minnano-driver-front

    steps:
      - checkout

      - run:
          name: Checking the Node.js version
          command: |
            node --version

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: Initializing dependencies
          command: |
            yarn install

      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Build the app
          command: |
            unset CI
            yarn build

      - slack/status:
          channel: ${SLACK_CHANNEL}
          webhook: ${SLACK_WEBHOOK}
          failure_message: ":red_circle: A $CIRCLE_JOB job has failed!"

      - slack/notify-on-failure:
          only_for_branches: develop

  # build and deploy to development
  build_and_deploy_to_develop:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/minnano-driver-front

    steps:
      - checkout

      - node/install:
          install-yarn: true

      - run:
          name: Checking Node.JS version
          command: |
            node --version

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: Initializing dependencies
          command: |
            yarn install

      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Initializing the Environment variables
          command: |
            echo "NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
            NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
            NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
            NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
            NEXT_PUBLIC_FIREBASE_MESSAGE_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGE_SENDER_ID
            NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
            NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
            NEXT_PUBLIC_APP_API_URL=$NEXT_PUBLIC_APP_API_URL
            NEXT_PUBLIC_CMS_URL=$NEXT_PUBLIC_CMS_URL
            NEXT_PUBLIC_ENVIRONMENT=$NEXT_PUBLIC_ENVIRONMENT
            NEXT_PUBLIC_BASEURL=$NEXT_PUBLIC_BASEURL
            CONSUMER_HOST=$CONSUMER_HOST" > .env

      - run:
          name: Authenticating and configuring the Google Cloud Platform
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GCLOUD_ZONE}

      - run:
          name: Build minanaodriver package
          command: |
            unset CI
            yarn build

      - run:
          name: Deploy minananodriver package
          command: |
            gcloud app deploy app.yaml --project ${GCLOUD_PROJECT_ID} --quiet

      - run:
          name: Delete Old versions of App Engine
          command: |
            versions=$(gcloud app versions list \
              --service default \
              --sort-by '~VERSION.ID' \
              --format 'value(VERSION.ID)' | sed 1,3d)
            for version in $versions; do
              gcloud app versions delete "$version" \
                --service default \
                --quiet
            done

      - slack/status:
          channel: ${SLACK_CHANNEL}
          webhook: ${SLACK_WEBHOOK}
          failure_message: ":red_circle: A $CIRCLE_JOB job has failed!"

      - slack/notify-on-failure:
          only_for_branches: develop

    resource_class: medium

  # build and deploy to production
  build_and_deploy_to_production:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/minnano-driver-front

    steps:
      - checkout

      - node/install:
          install-yarn: true

      - run:
          name: Checking Node.JS version
          command: |
            node --version

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: Initializing dependencies
          command: |
            yarn install

      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Initializing the Environment variables
          command: |
            echo "NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
            NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
            NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
            NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
            NEXT_PUBLIC_FIREBASE_MESSAGE_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGE_SENDER_ID
            NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
            NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
            NEXT_PUBLIC_APP_API_URL=$NEXT_PUBLIC_APP_API_URL
            NEXT_PUBLIC_CMS_URL=$NEXT_PUBLIC_CMS_URL
            NEXT_PUBLIC_ENVIRONMENT=$NEXT_PUBLIC_ENVIRONMENT
            NEXT_PUBLIC_BASEURL=$NEXT_PUBLIC_BASEURL
            CONSUMER_HOST=$CONSUMER_HOST" > .env

      - run:
          name: Authenticating and configuring the Google Cloud Platform
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GCLOUD_ZONE}

      - run:
          name: Build minananodriver cms package
          command: |
            unset CI
            yarn build

      - run:
          name: Deploy minnanodriver cms package
          command: |
            gcloud app deploy app.yaml --project ${GCLOUD_PROJECT_ID} --quiet

      - run:
          name: Delete Old versions of App Engine
          command: |
            versions=$(gcloud app versions list \
              --service default \
              --sort-by '~VERSION.ID' \
              --format 'value(VERSION.ID)' | sed 1,3d)
            for version in $versions; do
              gcloud app versions delete "$version" \
                --service default \
                --quiet
            done

      - slack/status:
          channel: ${SLACK_CHANNEL}
          webhook: ${SLACK_WEBHOOK}
          failure_message: ":red_circle: A $CIRCLE_JOB job has failed!"

      - slack/notify-on-failure:
          only_for_branches: main

    resource_class: medium

orbs:
  slack: circleci/slack@3.4.2
  # for secondary image dependencies to google cloud sdk
  node: circleci/node@7.0.0

workflows:
  build-workflow:
    jobs:
      - build:
          context: minnano_driver_dev
          filters:
            branches:
              only:
                - /MIN-.*/
                - circleci

      - build_and_deploy_to_develop:
          context: minnano_driver_dev
          filters:
            branches:
              only:
                - develop
                - circleci

      - build_and_deploy_to_production:
          context: minnano_driver
          filters:
            tags:
              only:
                - /v[0-9].*/
            branches:
              ignore:
                - /.*/
